### PR TITLE
Add Github Actions build

### PR DESCRIPTION
**Pull request by gliptak**
https://github.com/gliptak/aws-support-tickets-aggregator/runs/473338126?check_suite_focus=true

### CODE REVIEW

**Comment by gliptak** [comment]
@rogergzousc @Snapchat please review

**Comment by rogergzousc** [comment]
Apologies for the wait, @gliptak . Internally we're consulting with the tools team on whether or not to adopt Github Actions as a CI for this repo, as they do not support Github Actions right now.

**Comment by gliptak** [comment]
@rogergzousc looking forward to hear back on this

**Comment by rogergzousc** [comment]
bitmoji

**Pull request merged**
